In [1]:
import numpy as np

def sigmoid(x) :
    return 1 / (1 + np.exp(-x))

def derivative_sigmoid(x) :
    return x * (1 - x)

In [2]:
X = np.array([[1, 0, 1, 0],
              [1, 0, 1, 1],
              [0, 1, 0, 1]])

y = np.array([[1], [1], [0]])


In [3]:
epoch = 5000
lr = 0.1

In [4]:
in_n = X.shape[1]
hidden_n = 3;
out_n = 1;

In [5]:
wh = np.random.uniform(size = (in_n, hidden_n))
bh = np.random.uniform(size = (1, hidden_n))
wout = np.random.uniform(size = (hidden_n, out_n))
bout = np.random.uniform(size = (1, out_n))

In [8]:
wh

array([[-0.92735085,  1.4551478 ,  1.39883902],
       [ 1.98990026, -1.12526465, -1.53711328],
       [-0.76071508,  1.94677223,  1.49706145],
       [ 0.7026408 , -0.68196602, -0.75603087]])

In [9]:
bh

array([[-0.68199496, -0.68060124, -0.04055626]])

In [10]:
wout

array([[-2.94978365],
       [ 3.08996376],
       [ 2.88148549]])

In [11]:
bout

array([[-1.20841975]])

In [22]:
for i in range(epoch) :
    hidden_in = np.dot(X, wh) + bh # X.wh + bh
    hidden_act = sigmoid(hidden_in)
    
    out_in = np.dot(hidden_act, wout) + bout # H.wout + bout
    out = sigmoid(out_in)
    
    error = y - out
    out_delta = error * derivative_sigmoid(out)
    
    hidden_error = out_delta.dot(wout.T)
    hidden_delta = hidden_error * derivative_sigmoid(hidden_act)
    
    wout += hidden_act.T.dot(out_delta) * lr
    bout += np.sum(out_delta) * lr
    wh += X.T.dot(hidden_delta) * lr
    bh += np.sum(hidden_delta) * lr
    
print(out)

[[0.99188645]
 [0.98623578]
 [0.01843167]]
